name: mniml
favicon: null
layout_spectrum: 0.30872
typography_spectrum: 0.47609
title: mniml consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#3b3b3b'
    - '#949494'
    - '#c5c5c5'
  brandStrength: 0.8040764818433672
  lightness: 0.8190840457100421
  saturation: 0.20976278721354902
  rhythmicContrast: 0.5
purpose: []
